### ISSUE TITLE
[check_ipa_replication] nsds5replicaLastUpdateStatus slice is incorrect

### ISSUE THREAD

**Issue by Popsiclestick** [opinkerfi/nagios-plugins#35]
The [code linked here](https://github.com/opinkerfi/nagios-plugins/blob/51c659990b377e135d77b9cf79c8ff3410824108/check_ipa/check_ipa_replication#L49-L51) does not provide anything useful in the returned slice `rhost[1]['nsds5replicaLastUpdateStatus'][0][:2]`

```
>> print(rhost[1]['nsds5replicaLastUpdateStatus'][0][:2])
# Full string = "Error (0) Replica acquired successfully"
>> Er
```

If you want to continue with the slice approach, you probably want something like this.
```
if rhost[1]['nsds5replicaLastUpdateStatus'][0][7:8] == "0":
    plugin.status(ok)
elif rhost[1]['nsds5replicaLastUpdateStatus'][0][7:8] == "1":
    plugin.status(ok)
```

**Comment by gardart** [comment]
fixed with https://github.com/opinkerfi/nagios-plugins/pull/36
